menu:
- {name: <b>'Insight'</b>, url: '/cv'}
- {name: <b>'Contact'</b>, url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/dukerosen'}
- {icon: 'twitter', link: 'https://twitter.com/hanchang630'}
- {icon: 'instagram', link: 'https://www.instagram.com/henry._.chang630/'}
- {icon: 'linkedin', link: 'www.linkedin.com/in/han-zhang-716a12a3'}

contacts:
- {name: 'HAN ZHANG', title: 'Computer science', department: 'Visual Arts & Media', phone: '(332) 248-8516', email: 'hernychang630@gmail.com', address: '770 Jackson Street, APT 421, Hoboken, NJ, 07030'}
